### ISSUE TITLE
Barista Docker Compose won't build

### ISSUE THREAD

**Issue by vsurge** [Optum/barista#4] opened 2020-01-21 16:33 UTC
### [Steps to Reproduce]
1. From the root of the barista repository isse `docker-compose -f ./docker-compose.yaml up`

### [Actual Behavior]
* Observe that the following error is thrown:

```
Building barista-base
Traceback (most recent call last):
  File "site-packages/docker/utils/build.py", line 96, in create_archive
PermissionError: [Errno 13] Permission denied: '/Users/vincilbishop/Documents/Code/Surge/UHG/UHG-Code/barista/barista-api/node_modules/all-unpacker/lsar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 159, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 100, in create_archive
OSError: Can not read file in context: /Users/vincilbishop/Documents/Code/Surge/UHG/UHG-Code/barista/barista-api/node_modules/all-unpacker/lsar
[16221] Failed to execute script docker-compose
```
### [Expected Behavior]
*  No error should be thrown and the Docker images should build and start.

### [Notes]
* This SO article quotes a permission problem after a user is added in the docker image: https://stackoverflow.com/questions/56784492/docker-compose-permissionerror-errno-13-permission-denied-manage-py
* A user is added on line:7 of the barista-base image: https://hub.docker.com/layers/rmolinger/barista-base/compose/images/sha256-769695e52bdfb5313071a80521c208cdf1f13f604f5c1a760eb25887cc53abaa

**Comment by pkn4645** [comment] 2020-02-11 20:30
@rolinge Is this still an issue?  Or do you have this working now?

**Comment by rolinge** [comment] 2020-02-11 22:09
Cant reproduce this problem and It appears to be from before code was merged into develop branch.

**Closed by rolinge** 2020-02-11 22:10 UTC
